name: Publish Release

on:
  push:
    tags:
      - "v*" # Trigger on version tags

jobs:
  publish-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Check version consistency
        run: |
          CODE_VERSION=$(python -c 'import klp; print(klp.__version__)')
          TAG_VERSION=${GITHUB_REF#refs/tags/v}

          echo "Code version: $CODE_VERSION"
          echo "Tag version: $TAG_VERSION"

          if [ "$CODE_VERSION" != "$TAG_VERSION" ]; then
            echo "Error: Version mismatch!"
            echo "Version in klp.py ($CODE_VERSION) does not match git tag ($TAG_VERSION)"
            exit 1
          fi

          echo "Version consistency check passed"

      - name: Create distribution archive
        run: |
          mkdir -p dist/examples
          cp LICENSE README.md klp.py pyproject.toml dist/
          cp examples/mylog.logfmt dist/examples/
          cd dist && zip -r ../klp-${{ github.ref_name }}.zip *

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            klp-${{ github.ref_name }}.zip
          omit_body: true
