name: Release and Publish

on:
  push:
    tags:
      - "v*"

jobs:
  release-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/klp-logviewer
    permissions:
      contents: write  # For creating GitHub release
      id-token: write  # For PyPI publishing

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Check version consistency
        run: |
          CODE_VERSION=$(python -c 'import klp; print(klp.__version__)')
          TAG_VERSION=${GITHUB_REF#refs/tags/v}

          echo "Code version: $CODE_VERSION"
          echo "Tag version: $TAG_VERSION"

          if [ "$CODE_VERSION" != "$TAG_VERSION" ]; then
            echo "Error: Version mismatch!"
            echo "Version in klp.py ($CODE_VERSION) does not match git tag ($TAG_VERSION)"
            exit 1
          fi

          echo "Version consistency check passed"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build

      # Create GitHub Release assets
      - name: Create distribution archive
        run: |
          mkdir -p dist/examples
          cp LICENSE README.md klp.py pyproject.toml dist/
          cp examples/mylog.logfmt dist/examples/
          cd dist && zip -r ../klp-${{ github.ref_name }}.zip *

      # Create GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            klp-${{ github.ref_name }}.zip
          omit_body: true

      # Build and publish to PyPI
      - name: Build package
        run: python -m build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1